name: SourceField GitHub Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  initialComment:
    name: Post initial PR Comment (calculating...)
    runs-on: ubuntu-latest
    steps:
      - name: Update or create PR comment
        run: |
          curl -s -X POST \
          -H "Content-Type: application/json" \
          -d '{ "query": "mutation { prCommentRiskScorePending(pr: {repoOwner: \"${{ github.event.repository.owner.login }}\", repoName: \"${{ github.event.repository.name }}\", prNumber: ${{ github.event.pull_request.number }} }) }" }' \
          https://cartographr-api.sourcefield.io/dev-hwkns-plumbr/graphql

  fetchLanguages:
    name: Fetch Languages in Repo
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.get-present-languages.outputs.LANGUAGES }}
    steps:
      - name: Get Present Languages
        id: get-present-languages
        run: echo "LANGUAGES=$(curl -s ${{ github.event.repository.languages_url }} | jq -r 'keys[]')" >> $GITHUB_OUTPUT

  getMergeBase:
    name: Get Merge Base
    runs-on: ubuntu-latest
    outputs:
      merge_base: ${{ steps.get-merge-base.outputs.MERGE_BASE }}
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get merge-base
        id: get-merge-base
        run: echo "MERGE_BASE=$(git merge-base origin/${{ github.base_ref }} HEAD)" >> $GITHUB_OUTPUT

  parsePython:
    name: Parse Python Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/lsif-python-pyright:e854776"
    needs:
      - fetchLanguages
      - getMergeBase
    if: contains(needs.fetchLanguages.outputs.languages, 'Python')
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          lsif-python index --project-name="${{ github.repository }}" --output="lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-python
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          lsif-python index --project-name="${{ github.repository }}" --output="lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-python
          path: lsif-output-head.json
          retention-days: 1

  parseTypeScript:
    name: Parse TypeScript Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/sourcefield-lsif-typescript:014b3f5"
    needs:
      - fetchLanguages
      - getMergeBase
    if: contains(needs.fetchLanguages.outputs.languages, 'TypeScript')
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          lsif-typescript index --output="lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-typescript
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          lsif-typescript index --output="lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-typescript
          path: lsif-output-head.json
          retention-days: 1

  parseJavaScript:
    name: Parse JavaScript Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/sourcefield-lsif-typescript:014b3f5"
    needs:
      - fetchLanguages
      - getMergeBase
    if: contains(needs.fetchLanguages.outputs.languages, 'JavaScript')
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          lsif-typescript index --infer-tsconfig --output="lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-javascript
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          lsif-typescript index --infer-tsconfig --output="lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-javascript
          path: lsif-output-head.json
          retention-days: 1

  parseJava:
    name: Parse Java Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/sourcefield-lsif-java:0adeb7c"
    needs:
      - fetchLanguages
      - getMergeBase
    if: contains(needs.fetchLanguages.outputs.languages, 'Java') && !contains(needs.fetchLanguages.outputs.languages, 'JavaScript')
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          java \
          -Dlog4j.configurationFile=file:/sourcefield/src/log4j2.xml \
          -jar /sourcefield/target/sourcefield-lsif-java-1.0-SNAPSHOT-jar-with-dependencies.jar \
          -d="${PWD}" -o="${PWD}/lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-java
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          java \
          -Dlog4j.configurationFile=file:/sourcefield/src/log4j2.xml \
          -jar /sourcefield/target/sourcefield-lsif-java-1.0-SNAPSHOT-jar-with-dependencies.jar \
          -d="${PWD}" -o="${PWD}/lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-java
          path: lsif-output-head.json
          retention-days: 1

  parseGo:
    name: Parse Go Maps
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/sourcefield-lsif-go:57d9af0"
    needs:
      - fetchLanguages
      - getMergeBase
    if: contains(needs.fetchLanguages.outputs.languages, 'Go')
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run LSIF parser on base ref
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          lsif-go --output="lsif-output-base.json"
      - name: Upload map for base commit
        uses: actions/upload-artifact@v3
        with:
          name: map-base-go
          path: lsif-output-base.json
          retention-days: 1
      - name: Run LSIF parser on head ref
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          lsif-go --output="lsif-output-head.json"
      - name: Upload map for head commit
        uses: actions/upload-artifact@v3
        with:
          name: map-head-go
          path: lsif-output-head.json
          retention-days: 1

  processMapsPython:
    name: Process and Diff Maps (Python)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:2103e57"
    needs:
      - fetchLanguages
      - getMergeBase
      - parsePython
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        run: |
          # see https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-python
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-python
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --backend_url="$GRAPHQL_ENDPOINT"

  processMapsTypeScript:
    name: Process and Diff Maps (TypeScript)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:2103e57"
    needs:
      - fetchLanguages
      - getMergeBase
      - parseTypeScript
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        run: |
          # see https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-typescript
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-typescript
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --backend_url="$GRAPHQL_ENDPOINT"

  processMapsJavaScript:
    name: Process and Diff Maps (JavaScript)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:2103e57"
    needs:
      - fetchLanguages
      - getMergeBase
      - parseJavaScript
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        run: |
          # see https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-javascript
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-javascript
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --backend_url="$GRAPHQL_ENDPOINT"

  processMapsJava:
    name: Process and Diff Maps (Java)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:2103e57"
    needs:
      - fetchLanguages
      - getMergeBase
      - parseJava
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        run: |
          # see https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-java
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-java
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --backend_url="$GRAPHQL_ENDPOINT"

  processMapsGo:
    name: Process and Diff Maps (Go)
    runs-on: ubuntu-latest
    container:
      image: "us-docker.pkg.dev/plumbr/sourcefield-public/parse-processor/lsif-processor:2103e57"
    needs:
      - fetchLanguages
      - getMergeBase
      - parseGo
    steps:
      - name: Check out repo (full history)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set ownership
        run: |
          # see https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
      - name: Download base map
        uses: actions/download-artifact@v3
        with:
          name: map-base-go
      - name: Run parse processor on base map
        run: |
          git -c advice.detachedHead=false checkout ${{ needs.getMergeBase.outputs.merge_base }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-base.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/base.pickle"
      - name: Download head map
        uses: actions/download-artifact@v3
        with:
          name: map-head-go
      - name: Run parse processor on head map
        run: |
          git -c advice.detachedHead=false checkout ${{ github.event.pull_request.head.sha }}
          grep -rn "^\s*# ::> " . > /possible_annotations.txt || true
          cd /sourcefield
          python3 -m processor.python \
          --filename="${GITHUB_WORKSPACE}/lsif-output-head.json" \
          - run \
          --write_to_file=True \
          --map_output_file="/sourcefield/head.pickle"
      - name: Get diff
        run: |
          git diff origin/${{ github.base_ref }}...${{ github.event.pull_request.head.sha }} > /sourcefield/diff.txt
          ls -lah /sourcefield
      - name: Diff maps and report metrics to backend
        run: |
          cd /sourcefield
          python3 -m processor.mapdiff.commands - diff_maps_and_report_metrics \
          --map1=/sourcefield/base.pickle \
          --map2=/sourcefield/head.pickle \
          --diff=/sourcefield/diff.txt \
          --backend_url="$GRAPHQL_ENDPOINT"
